automation:
- id: dbf61284-7231-4eec-9218-b56c71666130
  alias: Frog Filter On
  mode: single
  trigger:
    platform: time
    at: "02:00:00"
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.frog_filter

- id: 48511dbc-9e68-48f9-a58c-01b559c8bcff
  alias: Frog Filter Off
  mode: single
  trigger:
    platform: time
    at: "08:00:00"
  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.frog_filter
