# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  packages: !include_dir_named packages

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

zha:
  zigpy_config:
    ota:
      ikea_provider: true

discovery:

media_player:
  - platform: openhome

input_text:
  snug_volume_last_command:
    name: ZHA Last Command - Snug Volume
  living_room_music_shortcut_last_command:
    name: ZHA Last Command - Living Room Music Shortcut
  living_room_dimmer_last_command:
    name: ZHA Last Command - Living Room Dimmer
  snug_dimmer_last_command:
    name: ZHA Last Command - Snug Dimmer
  kitchen_music_shortcut_last_command:
    name: ZHA Last Command - Kitchen Music Shortcut
  snug_music_shortcut_last_command:
    name: ZHA Last Command - Snug Music Shortcut
  back_garden_scene:
    name: Back Garden Scene
    initial: back_garden_off
  downstairs_hallway_scene:
    name: Downstairs Hallway Scene
    initial: downstairs_hallway_off
  downstairs_toilet_scene:
    name: Downstairs Toilet Scene
    initial: downstairs_toilet_bright
  front_garden_scene:
    name: Front Garden Scene
    initial: front_garden_off
  kitchen_scene:
    name: Kitchen Scene
    initial: kitchen_morning
  living_room_scene:
    name: Living Room Scene
    initial: living_room_off
  staircase_scene:
    name: Staircase Scene
    initial: stairs_off
  upstairs_hallway_scene:
    name: Upstairs Hallway Scene
    initial: upstairs_hallway_night
  snug_scene:
    name: Snug Scene
    initial: snug_chill

input_boolean:
  kitchen_bfl:
    name: Kitchen should be bright
    initial: off
  living_room_bfl:
    name: Living Room should be bright
    initial: off
  hallway_bfl:
    name: Hallway should be bright
    initial: off
  snug_bfl:
    name: Snug should be bright
    initial: off

light:
  - platform: group
    name: Kitchen Lights
    entities:
      - light.worktop_left_light_4
      - light.worktop_right_light_2
      - light.worktop_tumble_dryer_light_3
      - light.kitchen_main
      - light.kitchen_under_cupboards
      - light.kitchen_under_tall_cupboards
      - light.back_garden_light
  - platform: group
    name: Snug Lights
    entities:
      - light.lava_lamp
      - light.snug_1
      - light.snug_2
      - light.movie_shelf_light
      - light.snug_records_shelf
      - light.gaming_shelf_light_3
      - light.steampunk_lamp
      - light.snug_ceiling_strip_1
      - light.snug_ceiling_strip_2
  - platform: switch
    name: Snug Lava Lamp
    entity_id: switch.lava_lamp
  - platform: switch
    name: Snug Records Shelf
    entity_id: switch.records_light_switch