vacuum_hallway:
  alias: Clean the hall
  mode: single
  sequence:
  - service: neato.custom_cleaning
    data:
      entity_id: vacuum.neato
      mode: 2
      navigation: 3
      zone: Hallway
vacuum_kitchen:
  alias: Clean the kitchen
  mode: single
  sequence:
  - service: neato.custom_cleaning
    data:
      entity_id: vacuum.neato
      mode: 2
      navigation: 3
      zone: Kitchen
vacuum_living_room:
  alias: Clean the living room
  mode: single
  sequence:
  - service: neato.custom_cleaning
    data:
      entity_id: vacuum.neato
      mode: 2
      navigation: 3
      zone: Living Room
vacuum_toilet:
  alias: Clean the toilet
  mode: single
  sequence:
  - service: neato.custom_cleaning
    data:
      entity_id: vacuum.neato
      mode: 2
      navigation: 3
      zone: Toilet
vacuum_stop:
  alias: Stop cleaning
  mode: single
  sequence:
  - service: vacuum.return_to_base
    data:
      entity_id: vacuum.neato
projector_on:
  alias: Projector On
  mode: restart
  sequence:
  - service: switch.turn_on
    target:
      entity_id: switch.benq_projector
  - service: cover.close_cover
    target:
      entity_id: cover.snug_blind_cover
  - service: script.turn_on
    target:
      entity_id: script.snug_surround
projector_off:
  alias: Projector Off
  mode: restart
  sequence:
  - service: switch.turn_off
    target:
      entity_id: switch.benq_projector
  - service: cover.open_cover
    target:
      entity_id: cover.snug_blind_cover
  - delay:
      milliseconds: 30
  - service: switch.turn_off
    target:
      entity_id: switch.benq_projector
snug_surround:
  alias: Surround Sound
  mode: restart
  sequence:
  - service: switch.turn_off
    target:
      entity_id: switch.lp12
    data: {}
  - service: switch.turn_on
    target:
      entity_id: switch.snug_hifi
    data: {}
  - service: input_select.select_option
    data:
      option: snug_movie
    target:
      entity_id: input_select.snug_scene
  - wait_template: '{{ states(''media_player.openhome_uuid_4c494e4e_0026_0f22_2963_01387403013f'')
      != ''unavailable'' }}'
  - service: media_player.select_source
    data:
      source: Arcam
    target:
      entity_id: media_player.openhome_uuid_4c494e4e_0026_0f22_2963_01387403013f
  - service: media_player.turn_on
    data: {}
    target:
      entity_id: media_player.arcam_fmj_192_168_4_65_zone_1
  - delay:
      milliseconds: 30
  - service: media_player.select_source
    data:
      source: BD
    target:
      entity_id: media_player.arcam_fmj_192_168_4_65_zone_1
  - service: media_player.turn_on
    target:
      entity_id: media_player.snug
    data: {}
  - if:
    - condition: not
      conditions:
      - condition: state
        entity_id: switch.benq_projector
        state: 'on'
    then:
    - service: media_player.turn_on
      data: {}
      target:
        entity_id: media_player.samsung_the_frame_43
snug_music:
  alias: HiFi
  mode: restart
  sequence:
  - service: switch.turn_off
    target:
      entity_id: switch.lp12
    data: {}
  - service: switch.turn_on
    target:
      entity_id: switch.snug_hifi
    data: {}
  - service: input_select.select_option
    data:
      option: snug_music
    target:
      entity_id: input_select.snug_scene
  - wait_template: '{{ states(''media_player.openhome_uuid_4c494e4e_0026_0f22_2963_01387403013f'')
      != ''unavailable'' }}'
  - service: media_player.turn_off
    target:
      entity_id: media_player.arcam_fmj_192_168_1_52_zone_1_2
    data: {}
snug_lp12:
  alias: LP12
  mode: restart
  sequence:
  - service: switch.turn_on
    target:
      entity_id: switch.lp12
    data: {}
  - service: switch.turn_on
    target:
      entity_id: switch.snug_hifi
    data: {}
  - service: input_select.select_option
    data:
      option: snug_lp12
    target:
      entity_id: input_select.snug_scene
  - wait_template: '{{ states(''media_player.openhome_uuid_4c494e4e_0026_0f22_2963_01387403013f'')
      != ''unavailable'' }}'
  - service: media_player.select_source
    data:
      source: LP12
    target:
      entity_id: media_player.openhome_uuid_4c494e4e_0026_0f22_2963_01387403013f
  - service: media_player.turn_off
    target:
      entity_id: media_player.arcam_fmj_192_168_1_52_zone_1_2
    data: {}
snug_off:
  alias: Snug Off
  mode: restart
  sequence:
  - service: input_select.select_option
    data:
      option: snug_chill
    target:
      entity_id: input_select.snug_scene
  - service: script.turn_on
    target:
      entity_id: script.projector_off
    data: {}
  - service: switch.turn_off
    data:
      entity_id: switch.lp12
  - service: switch.turn_off
    data:
      entity_id: switch.snug_hifi
  - service: media_player.turn_off
    target:
      entity_id: media_player.snug
    data: {}
  - delay:
      seconds: 5
  - service: media_player.turn_off
    target:
      entity_id: media_player.samsung_the_frame_43
    data: {}
